import type { JadePack, JadePackScores, JadeStoreCategory, PriceTier, JadeRarity } from './jadeTypes';

// Helper to generate packs
function pack(
  id: string, name: string, subtitle: string,
  category: JadeStoreCategory, rarity: JadeRarity, priceTier: PriceTier,
  priceDiamonds: number, icon: string, theme: string,
  rewards: { name: string; icon: string; rarity: JadeRarity; qty: number; guaranteed: boolean }[],
  opts: Partial<JadePack> = {}
): JadePack {
  return {
    id, name, subtitle, category, rarity, priceTier, priceDiamonds, icon,
    visualTheme: theme,
    coreRewards: rewards.map(r => ({ name: r.name, icon: r.icon, rarity: r.rarity, quantity: r.qty, guaranteed: r.guaranteed })),
    pityContribution: priceTier === 'micro' ? 1 : priceTier === 'entry' ? 2 : priceTier === 'core' ? 3 : priceTier === 'mid' ? 5 : priceTier === 'elite' ? 8 : priceTier === 'whale' ? 15 : 25,
    targetSegment: opts.targetSegment ?? 'all',
    rotationType: opts.rotationType ?? 'permanent',
    bestValue: opts.bestValue ?? false,
    mostPopular: opts.mostPopular ?? false,
    featured: opts.featured ?? false,
    isLimited: opts.isLimited ?? false,
    isNew: opts.isNew ?? false,
    seasonal: opts.seasonal,
    priceUsd: opts.priceUsd,
    purchaseLimit: opts.purchaseLimit,
    availabilityHours: opts.availabilityHours,
    bonusRewards: opts.bonusRewards,
    scores: opts.scores ?? {
      visual_desirability: 5, perceived_value: 5, real_margin: 5,
      beginner_friendliness: 5, collector_appeal: 5, whale_appeal: 5,
      urgency_strength: 5, prestige_strength: 5, retention_contribution: 5,
      overall_attractiveness: 5,
    },
    emotionalHook: opts.emotionalHook ?? '',
    adminNotes: opts.adminNotes ?? '',
  };
}

// ═══════════════════════════════════════════
// FULL 120-PACK CATALOG
// ═══════════════════════════════════════════

export const JADE_STORE_PACKS: JadePack[] = [

  // ────── BEGINNER PACKS (12) ──────
  pack('bg-01','First Carve Starter','Begin your jade journey','beginner_packs','rough','entry',50,'🌱','jade-green',
    [{ name:'Raw Jade Shard',icon:'💎',rarity:'rough',qty:5,guaranteed:true },{ name:'Basic Chisel',icon:'🔨',rarity:'rough',qty:1,guaranteed:true }],
    { bestValue:true, isNew:true, purchaseLimit:1, targetSegment:'new_user', emotionalHook:'Your first step into jade mastery', scores:{ visual_desirability:6,perceived_value:9,real_margin:4,beginner_friendliness:10,collector_appeal:2,whale_appeal:1,urgency_strength:3,prestige_strength:2,retention_contribution:8,overall_attractiveness:7 } }),
  pack('bg-02','New Artisan Bundle','Everything to begin carving','beginner_packs','polished','entry',80,'🎁','jade-green',
    [{ name:'Polished Jade Block',icon:'🪨',rarity:'polished',qty:2,guaranteed:true },{ name:'Coolant Flask',icon:'🧪',rarity:'rough',qty:3,guaranteed:true },{ name:'Vault Key Fragment',icon:'🔑',rarity:'rough',qty:2,guaranteed:true }],
    { bestValue:true, purchaseLimit:1, targetSegment:'new_user', emotionalHook:'A generous welcome to the atelier', scores:{ visual_desirability:7,perceived_value:9,real_margin:3,beginner_friendliness:10,collector_appeal:3,whale_appeal:1,urgency_strength:2,prestige_strength:3,retention_contribution:9,overall_attractiveness:8 } }),
  pack('bg-03','Welcome Vault Offer','Your first vault opening','beginner_packs','refined','entry',120,'🏛️','gold-jade',
    [{ name:'Gilded Vault Key',icon:'🗝️',rarity:'refined',qty:1,guaranteed:true },{ name:'Jade Dust',icon:'✨',rarity:'rough',qty:100,guaranteed:true }],
    { mostPopular:true, purchaseLimit:1, targetSegment:'new_user', emotionalHook:'See the vault glow for the first time', scores:{ visual_desirability:8,perceived_value:8,real_margin:5,beginner_friendliness:9,collector_appeal:4,whale_appeal:1,urgency_strength:4,prestige_strength:5,retention_contribution:8,overall_attractiveness:8 } }),
  pack('bg-04','First Signature Pack','Claim your jade mark','beginner_packs','polished','entry',60,'✍️','jade-green',
    [{ name:'Jade Signature Ink',icon:'🖋️',rarity:'polished',qty:1,guaranteed:true },{ name:'Raw Jade Shard',icon:'💎',rarity:'rough',qty:3,guaranteed:true }],
    { purchaseLimit:1, targetSegment:'new_user', emotionalHook:'Your lineage begins here', scores:{ visual_desirability:6,perceived_value:7,real_margin:6,beginner_friendliness:9,collector_appeal:5,whale_appeal:1,urgency_strength:2,prestige_strength:6,retention_contribution:7,overall_attractiveness:6 } }),
  pack('bg-05','Apprentice Workshop','Basic tools collection','beginner_packs','rough','micro',30,'🧰','jade-green',
    [{ name:'Basic Polish Kit',icon:'🧽',rarity:'rough',qty:2,guaranteed:true },{ name:'Jade Fragment',icon:'💠',rarity:'rough',qty:10,guaranteed:true }],
    { targetSegment:'new_user', emotionalHook:'Affordable start', scores:{ visual_desirability:4,perceived_value:7,real_margin:5,beginner_friendliness:10,collector_appeal:1,whale_appeal:1,urgency_strength:1,prestige_strength:1,retention_contribution:6,overall_attractiveness:5 } }),
  pack('bg-06','Jade Primer','Learn the sacred art','beginner_packs','rough','micro',20,'📖','jade-green',
    [{ name:'Jade Knowledge Scroll',icon:'📜',rarity:'rough',qty:1,guaranteed:true },{ name:'Jade Fragment',icon:'💠',rarity:'rough',qty:5,guaranteed:true }],
    { targetSegment:'new_user', emotionalHook:'Knowledge is the first luxury', scores:{ visual_desirability:3,perceived_value:6,real_margin:7,beginner_friendliness:10,collector_appeal:1,whale_appeal:1,urgency_strength:1,prestige_strength:1,retention_contribution:5,overall_attractiveness:4 } }),
  pack('bg-07','Seedling Vault Entry','Tiny vault taste','beginner_packs','rough','micro',40,'🌿','jade-green',
    [{ name:'Mini Vault Token',icon:'🎟️',rarity:'rough',qty:1,guaranteed:true }],
    { targetSegment:'new_user', emotionalHook:'One peek inside the vault', scores:{ visual_desirability:5,perceived_value:6,real_margin:6,beginner_friendliness:9,collector_appeal:2,whale_appeal:1,urgency_strength:3,prestige_strength:2,retention_contribution:6,overall_attractiveness:5 } }),
  pack('bg-08','Jade Dust Starter','A handful of dust','beginner_packs','rough','micro',15,'✨','jade-green',
    [{ name:'Jade Dust',icon:'✨',rarity:'rough',qty:50,guaranteed:true }],
    { targetSegment:'new_user', emotionalHook:'Every artisan needs dust', scores:{ visual_desirability:3,perceived_value:5,real_margin:8,beginner_friendliness:10,collector_appeal:1,whale_appeal:1,urgency_strength:1,prestige_strength:1,retention_contribution:4,overall_attractiveness:4 } }),
  pack('bg-09','Onboarding Chest','Curated for newcomers','beginner_packs','polished','entry',90,'🎁','jade-gold',
    [{ name:'Polished Jade Block',icon:'🪨',rarity:'polished',qty:1,guaranteed:true },{ name:'Basic Chisel',icon:'🔨',rarity:'rough',qty:1,guaranteed:true },{ name:'Coolant Flask',icon:'🧪',rarity:'rough',qty:2,guaranteed:true },{ name:'Jade Dust',icon:'✨',rarity:'rough',qty:75,guaranteed:true }],
    { bestValue:true, purchaseLimit:1, targetSegment:'new_user', emotionalHook:'Everything you need in one chest', scores:{ visual_desirability:7,perceived_value:9,real_margin:3,beginner_friendliness:10,collector_appeal:2,whale_appeal:1,urgency_strength:2,prestige_strength:3,retention_contribution:9,overall_attractiveness:7 } }),
  pack('bg-10','Mentor\'s Gift','A master\'s blessing','beginner_packs','refined','entry',150,'🎓','jade-gold',
    [{ name:'Refined Jade Piece',icon:'💎',rarity:'refined',qty:1,guaranteed:true },{ name:'Precision Chisel',icon:'⛏️',rarity:'polished',qty:1,guaranteed:true },{ name:'Jade Dust',icon:'✨',rarity:'rough',qty:150,guaranteed:true }],
    { featured:true, purchaseLimit:1, targetSegment:'new_user', emotionalHook:'Start with a master\'s blessing', scores:{ visual_desirability:8,perceived_value:9,real_margin:4,beginner_friendliness:8,collector_appeal:4,whale_appeal:1,urgency_strength:3,prestige_strength:5,retention_contribution:9,overall_attractiveness:8 } }),
  pack('bg-11','Safe Harbor Kit','Recovery-friendly start','beginner_packs','rough','entry',70,'⚓','jade-green',
    [{ name:'Fracture Shield',icon:'🛡️',rarity:'polished',qty:1,guaranteed:true },{ name:'Raw Jade Shard',icon:'💎',rarity:'rough',qty:3,guaranteed:true },{ name:'Coolant Flask',icon:'🧪',rarity:'rough',qty:2,guaranteed:true }],
    { purchaseLimit:1, targetSegment:'cautious_new', emotionalHook:'Begin without fear of loss', scores:{ visual_desirability:5,perceived_value:8,real_margin:5,beginner_friendliness:10,collector_appeal:2,whale_appeal:1,urgency_strength:1,prestige_strength:2,retention_contribution:8,overall_attractiveness:6 } }),
  pack('bg-12','Lucky Start Pack','Fortune favors the bold','beginner_packs','polished','entry',100,'🍀','jade-gold',
    [{ name:'Lucky Jade Shard',icon:'🍀',rarity:'polished',qty:2,guaranteed:true },{ name:'Vault Key Fragment',icon:'🔑',rarity:'rough',qty:3,guaranteed:true },{ name:'Jade Dust',icon:'✨',rarity:'rough',qty:100,guaranteed:true }],
    { isNew:true, purchaseLimit:1, targetSegment:'new_user', emotionalHook:'Fortune favors the bold', scores:{ visual_desirability:7,perceived_value:8,real_margin:5,beginner_friendliness:9,collector_appeal:3,whale_appeal:1,urgency_strength:3,prestige_strength:3,retention_contribution:7,overall_attractiveness:7 } }),

  // ────── VAULT PACKS (20) ──────
  pack('vp-01','Shard Spark Pack','A flicker of jade','vault_packs','rough','micro',10,'⚡','jade-green',
    [{ name:'Raw Jade Shard',icon:'💎',rarity:'rough',qty:1,guaranteed:true }],
    { targetSegment:'impulse', emotionalHook:'Just one more shard...', scores:{ visual_desirability:3,perceived_value:4,real_margin:9,beginner_friendliness:8,collector_appeal:2,whale_appeal:1,urgency_strength:2,prestige_strength:1,retention_contribution:4,overall_attractiveness:4 } }),
  pack('vp-02','Jade Fragment Trio','Three pieces of potential','vault_packs','rough','micro',25,'💠','jade-green',
    [{ name:'Raw Jade Shard',icon:'💎',rarity:'rough',qty:3,guaranteed:true }],
    { targetSegment:'casual', emotionalHook:'Three chances at greatness', scores:{ visual_desirability:4,perceived_value:5,real_margin:8,beginner_friendliness:7,collector_appeal:2,whale_appeal:1,urgency_strength:2,prestige_strength:1,retention_contribution:5,overall_attractiveness:4 } }),
  pack('vp-03','Gilded Vault Key','Open the golden vault','vault_packs','gilded','core',200,'🗝️','gold',
    [{ name:'Gilded Vault Key',icon:'🗝️',rarity:'gilded',qty:1,guaranteed:true }],
    { mostPopular:true, targetSegment:'regular', emotionalHook:'The golden door awaits', scores:{ visual_desirability:8,perceived_value:7,real_margin:6,beginner_friendliness:5,collector_appeal:6,whale_appeal:3,urgency_strength:5,prestige_strength:7,retention_contribution:7,overall_attractiveness:7 } }),
  pack('vp-04','Refined Vault Bundle','Curated jade selection','vault_packs','refined','core',300,'📦','jade-gold',
    [{ name:'Refined Jade Block',icon:'💎',rarity:'refined',qty:2,guaranteed:true },{ name:'Vault Key Fragment',icon:'🔑',rarity:'rough',qty:5,guaranteed:true }],
    { bestValue:true, targetSegment:'regular', emotionalHook:'Curated excellence', scores:{ visual_desirability:7,perceived_value:8,real_margin:5,beginner_friendliness:5,collector_appeal:5,whale_appeal:3,urgency_strength:3,prestige_strength:5,retention_contribution:7,overall_attractiveness:7 } }),
  pack('vp-05','Sovereign Vault Entry','Access the sovereign tier','vault_packs','sovereign','elite',800,'👑','royal-purple',
    [{ name:'Sovereign Vault Key',icon:'🔐',rarity:'sovereign',qty:1,guaranteed:true },{ name:'Jade Dust',icon:'✨',rarity:'rough',qty:500,guaranteed:true }],
    { featured:true, targetSegment:'premium', emotionalHook:'Step into sovereign territory', scores:{ visual_desirability:9,perceived_value:8,real_margin:6,beginner_friendliness:2,collector_appeal:8,whale_appeal:6,urgency_strength:6,prestige_strength:9,retention_contribution:7,overall_attractiveness:8 } }),
  pack('vp-06','Singularity Chance Pack','Chase the impossible','vault_packs','imperial','elite',1200,'🌌','cosmic',
    [{ name:'Imperial Vault Key',icon:'✴️',rarity:'imperial',qty:1,guaranteed:true },{ name:'Singularity Shard Fragment',icon:'🌟',rarity:'sovereign',qty:1,guaranteed:false }],
    { isLimited:true, targetSegment:'collector', emotionalHook:'0.3% chance of singularity-grade jade', scores:{ visual_desirability:10,perceived_value:7,real_margin:7,beginner_friendliness:1,collector_appeal:10,whale_appeal:8,urgency_strength:8,prestige_strength:10,retention_contribution:6,overall_attractiveness:8 } }),
  pack('vp-07','Daily Jade Drop','Your daily reveal','vault_packs','rough','micro',15,'🌅','jade-green',
    [{ name:'Random Jade Shard',icon:'💎',rarity:'rough',qty:1,guaranteed:true }],
    { rotationType:'weekly', targetSegment:'daily', emotionalHook:'Come back every day', scores:{ visual_desirability:4,perceived_value:5,real_margin:7,beginner_friendliness:7,collector_appeal:2,whale_appeal:1,urgency_strength:3,prestige_strength:1,retention_contribution:8,overall_attractiveness:5 } }),
  pack('vp-08','Five-Pull Bundle','Five reveals, one price','vault_packs','polished','core',220,'🎰','jade-green',
    [{ name:'Vault Reveal Token',icon:'🎫',rarity:'polished',qty:5,guaranteed:true }],
    { bestValue:true, targetSegment:'regular', emotionalHook:'Save 12% over singles', scores:{ visual_desirability:6,perceived_value:8,real_margin:5,beginner_friendliness:5,collector_appeal:4,whale_appeal:2,urgency_strength:3,prestige_strength:3,retention_contribution:7,overall_attractiveness:6 } }),
  pack('vp-09','Ten-Pull Prestige','Ten reveals plus bonus','vault_packs','refined','mid',400,'🎰','gold-jade',
    [{ name:'Vault Reveal Token',icon:'🎫',rarity:'polished',qty:10,guaranteed:true },{ name:'Guaranteed Refined+',icon:'💎',rarity:'refined',qty:1,guaranteed:true }],
    { mostPopular:true, targetSegment:'spender', emotionalHook:'One guaranteed refined or above', scores:{ visual_desirability:8,perceived_value:9,real_margin:5,beginner_friendliness:3,collector_appeal:6,whale_appeal:4,urgency_strength:4,prestige_strength:5,retention_contribution:8,overall_attractiveness:8 } }),
  pack('vp-10','Jade Block Select','Choose your grade','vault_packs','refined','core',350,'🪨','jade-green',
    [{ name:'Jade Block (Player\'s Choice)',icon:'🪨',rarity:'refined',qty:1,guaranteed:true }],
    { targetSegment:'experienced', emotionalHook:'Choose exactly what you need', scores:{ visual_desirability:6,perceived_value:7,real_margin:5,beginner_friendliness:4,collector_appeal:5,whale_appeal:3,urgency_strength:2,prestige_strength:4,retention_contribution:6,overall_attractiveness:6 } }),
  pack('vp-11','Raw Jade Dozen','Twelve raw shards','vault_packs','rough','core',100,'💎','jade-green',
    [{ name:'Raw Jade Shard',icon:'💎',rarity:'rough',qty:12,guaranteed:true }],
    { targetSegment:'regular', emotionalHook:'Bulk rough jade for carving practice', scores:{ visual_desirability:4,perceived_value:7,real_margin:6,beginner_friendliness:6,collector_appeal:2,whale_appeal:1,urgency_strength:2,prestige_strength:1,retention_contribution:6,overall_attractiveness:5 } }),
  pack('vp-12','Polished Quartet','Four polished blocks','vault_packs','polished','core',180,'🪨','jade-green',
    [{ name:'Polished Jade Block',icon:'🪨',rarity:'polished',qty:4,guaranteed:true }],
    { targetSegment:'regular', emotionalHook:'Ready for refinement', scores:{ visual_desirability:5,perceived_value:7,real_margin:6,beginner_friendliness:5,collector_appeal:3,whale_appeal:2,urgency_strength:2,prestige_strength:3,retention_contribution:6,overall_attractiveness:5 } }),
  pack('vp-13','Golden Reveal Box','Guaranteed gilded jade','vault_packs','gilded','mid',500,'📦','gold',
    [{ name:'Gilded Jade Piece',icon:'💎',rarity:'gilded',qty:1,guaranteed:true },{ name:'Jade Dust',icon:'✨',rarity:'rough',qty:200,guaranteed:true }],
    { targetSegment:'premium', emotionalHook:'Gold-tier guaranteed', scores:{ visual_desirability:8,perceived_value:7,real_margin:6,beginner_friendliness:3,collector_appeal:7,whale_appeal:4,urgency_strength:4,prestige_strength:7,retention_contribution:6,overall_attractiveness:7 } }),
  pack('vp-14','Vault Marathon Pack','20 reveals for grinders','vault_packs','refined','mid',750,'🏃','jade-gold',
    [{ name:'Vault Reveal Token',icon:'🎫',rarity:'polished',qty:20,guaranteed:true },{ name:'Guaranteed Gilded+',icon:'💎',rarity:'gilded',qty:1,guaranteed:true }],
    { targetSegment:'grinder', emotionalHook:'Marathon to gilded glory', scores:{ visual_desirability:7,perceived_value:9,real_margin:4,beginner_friendliness:2,collector_appeal:5,whale_appeal:5,urgency_strength:3,prestige_strength:5,retention_contribution:8,overall_attractiveness:7 } }),
  pack('vp-15','Jade Dust Pouch','500 jade dust','vault_packs','rough','core',150,'👝','jade-green',
    [{ name:'Jade Dust',icon:'✨',rarity:'rough',qty:500,guaranteed:true }],
    { targetSegment:'crafter', emotionalHook:'Fuel for the atelier', scores:{ visual_desirability:4,perceived_value:6,real_margin:7,beginner_friendliness:6,collector_appeal:2,whale_appeal:1,urgency_strength:2,prestige_strength:2,retention_contribution:6,overall_attractiveness:5 } }),
  pack('vp-16','Jade Dust Chest','2000 jade dust','vault_packs','polished','mid',500,'💰','jade-green',
    [{ name:'Jade Dust',icon:'✨',rarity:'rough',qty:2000,guaranteed:true }],
    { targetSegment:'crafter', emotionalHook:'An artisan\'s war chest', scores:{ visual_desirability:5,perceived_value:7,real_margin:6,beginner_friendliness:4,collector_appeal:2,whale_appeal:2,urgency_strength:2,prestige_strength:3,retention_contribution:7,overall_attractiveness:5 } }),
  pack('vp-17','Double Gilded Chest','Two gilded pieces','vault_packs','gilded','elite',900,'🏆','gold',
    [{ name:'Gilded Jade Piece',icon:'💎',rarity:'gilded',qty:2,guaranteed:true },{ name:'Jade Dust',icon:'✨',rarity:'rough',qty:300,guaranteed:true }],
    { targetSegment:'premium', emotionalHook:'Double the gold-tier prestige', scores:{ visual_desirability:9,perceived_value:8,real_margin:5,beginner_friendliness:2,collector_appeal:7,whale_appeal:5,urgency_strength:4,prestige_strength:8,retention_contribution:6,overall_attractiveness:7 } }),
  pack('vp-18','Imperial Key Bundle','Three imperial vault keys','vault_packs','imperial','whale',2500,'🔐','cosmic',
    [{ name:'Imperial Vault Key',icon:'✴️',rarity:'imperial',qty:3,guaranteed:true },{ name:'Jade Dust',icon:'✨',rarity:'rough',qty:1000,guaranteed:true }],
    { priceUsd:49.99, targetSegment:'whale', emotionalHook:'Three shots at imperial glory', scores:{ visual_desirability:9,perceived_value:7,real_margin:7,beginner_friendliness:1,collector_appeal:9,whale_appeal:8,urgency_strength:5,prestige_strength:9,retention_contribution:5,overall_attractiveness:8 } }),
  pack('vp-19','Vault Blitz Pack','Flash 30-min offer','vault_packs','refined','core',250,'⏱️','jade-gold',
    [{ name:'Refined Jade Block',icon:'💎',rarity:'refined',qty:3,guaranteed:true },{ name:'Vault Key Fragment',icon:'🔑',rarity:'rough',qty:3,guaranteed:true }],
    { rotationType:'flash', isLimited:true, availabilityHours:0.5, targetSegment:'impulse', emotionalHook:'Gone in 30 minutes', scores:{ visual_desirability:7,perceived_value:8,real_margin:5,beginner_friendliness:4,collector_appeal:4,whale_appeal:3,urgency_strength:10,prestige_strength:4,retention_contribution:6,overall_attractiveness:7 } }),
  pack('vp-20','Sovereign Revelation','Guaranteed sovereign jade','vault_packs','sovereign','whale',2000,'🌟','royal-purple',
    [{ name:'Sovereign Jade Piece',icon:'💎',rarity:'sovereign',qty:1,guaranteed:true },{ name:'Gilded Jade Piece',icon:'💎',rarity:'gilded',qty:2,guaranteed:true },{ name:'Jade Dust',icon:'✨',rarity:'rough',qty:800,guaranteed:true }],
    { priceUsd:39.99, featured:true, targetSegment:'whale', emotionalHook:'Sovereign-grade jade, guaranteed', scores:{ visual_desirability:10,perceived_value:9,real_margin:6,beginner_friendliness:1,collector_appeal:9,whale_appeal:9,urgency_strength:5,prestige_strength:10,retention_contribution:6,overall_attractiveness:9 } }),

  // ────── SOVEREIGN PACKS (10) ──────
  pack('sp-01','Reserve Stability Pack','Treasury-backed jade','sovereign_packs','gilded','mid',600,'🏛️','gold-jade',
    [{ name:'Reserve-Backed Jade Token',icon:'🏛️',rarity:'gilded',qty:1,guaranteed:true },{ name:'Stability Certificate',icon:'📜',rarity:'refined',qty:1,guaranteed:true }],
    { targetSegment:'investor', emotionalHook:'Backed by the sovereign fund', scores:{ visual_desirability:7,perceived_value:7,real_margin:6,beginner_friendliness:3,collector_appeal:6,whale_appeal:5,urgency_strength:3,prestige_strength:8,retention_contribution:6,overall_attractiveness:7 } }),
  pack('sp-02','Gold-Referenced Prestige','Gold-tier confidence','sovereign_packs','sovereign','elite',1500,'🥇','gold',
    [{ name:'Gold-Referenced Jade',icon:'🥇',rarity:'sovereign',qty:1,guaranteed:true },{ name:'Prestige Emblem',icon:'🏅',rarity:'gilded',qty:1,guaranteed:true }],
    { priceUsd:29.99, targetSegment:'premium', emotionalHook:'Jade that references gold benchmarks', scores:{ visual_desirability:9,perceived_value:8,real_margin:6,beginner_friendliness:1,collector_appeal:8,whale_appeal:7,urgency_strength:4,prestige_strength:10,retention_contribution:5,overall_attractiveness:8 } }),
  pack('sp-03','Treasury Alignment Pack','Sovereign fund aligned','sovereign_packs','gilded','mid',550,'📊','jade-gold',
    [{ name:'Treasury Alignment Token',icon:'📊',rarity:'gilded',qty:1,guaranteed:true },{ name:'Jade Dust',icon:'✨',rarity:'rough',qty:300,guaranteed:true }],
    { targetSegment:'strategic', emotionalHook:'Aligned with the sovereign treasury', scores:{ visual_desirability:6,perceived_value:6,real_margin:7,beginner_friendliness:2,collector_appeal:5,whale_appeal:4,urgency_strength:2,prestige_strength:7,retention_contribution:5,overall_attractiveness:6 } }),
  pack('sp-04','Platinum Reference Bundle','Platinum-tier prestige','sovereign_packs','sovereign','elite',1800,'💠','platinum',
    [{ name:'Platinum-Referenced Jade',icon:'💠',rarity:'sovereign',qty:1,guaranteed:true },{ name:'Sovereign Seal',icon:'🔏',rarity:'sovereign',qty:1,guaranteed:true }],
    { priceUsd:34.99, isLimited:true, targetSegment:'collector', emotionalHook:'Platinum-class reserve jade', scores:{ visual_desirability:9,perceived_value:8,real_margin:7,beginner_friendliness:1,collector_appeal:9,whale_appeal:8,urgency_strength:6,prestige_strength:10,retention_contribution:5,overall_attractiveness:8 } }),
  pack('sp-05','Sovereign Confidence Box','Trust the fund','sovereign_packs','refined','core',350,'🏦','jade-gold',
    [{ name:'Confidence Token',icon:'🏦',rarity:'refined',qty:2,guaranteed:true },{ name:'Jade Dust',icon:'✨',rarity:'rough',qty:200,guaranteed:true }],
    { targetSegment:'regular', emotionalHook:'Stability in every shard', scores:{ visual_desirability:6,perceived_value:7,real_margin:6,beginner_friendliness:4,collector_appeal:4,whale_appeal:3,urgency_strength:2,prestige_strength:6,retention_contribution:6,overall_attractiveness:6 } }),
  pack('sp-06','Dynasty Heir Pack','Lineage-grade jade','sovereign_packs','imperial','whale',3000,'👑','royal-purple',
    [{ name:'Imperial Lineage Jade',icon:'👑',rarity:'imperial',qty:1,guaranteed:true },{ name:'Dynasty Seal',icon:'🔏',rarity:'sovereign',qty:1,guaranteed:true },{ name:'Jade Dust',icon:'✨',rarity:'rough',qty:1500,guaranteed:true }],
    { priceUsd:59.99, featured:true, targetSegment:'whale', emotionalHook:'Start a dynasty', scores:{ visual_desirability:10,perceived_value:8,real_margin:7,beginner_friendliness:1,collector_appeal:10,whale_appeal:10,urgency_strength:5,prestige_strength:10,retention_contribution:6,overall_attractiveness:9 } }),
  pack('sp-07','Silver Prestige Pack','Silver-referenced jade','sovereign_packs','refined','core',280,'🥈','silver',
    [{ name:'Silver-Referenced Shard',icon:'🥈',rarity:'refined',qty:2,guaranteed:true }],
    { targetSegment:'regular', emotionalHook:'Accessible prestige', scores:{ visual_desirability:6,perceived_value:6,real_margin:6,beginner_friendliness:5,collector_appeal:4,whale_appeal:2,urgency_strength:2,prestige_strength:5,retention_contribution:5,overall_attractiveness:5 } }),
  pack('sp-08','Palladium Specialist','Rare metal reference','sovereign_packs','gilded','mid',700,'⚙️','platinum',
    [{ name:'Palladium-Referenced Jade',icon:'⚙️',rarity:'gilded',qty:1,guaranteed:true },{ name:'Specialist Seal',icon:'🔏',rarity:'refined',qty:1,guaranteed:true }],
    { isLimited:true, targetSegment:'specialist', emotionalHook:'For the precious metal connoisseur', scores:{ visual_desirability:7,perceived_value:7,real_margin:7,beginner_friendliness:1,collector_appeal:8,whale_appeal:5,urgency_strength:5,prestige_strength:8,retention_contribution:4,overall_attractiveness:7 } }),
  pack('sp-09','Reserve Mini','Small sovereign taste','sovereign_packs','polished','entry',120,'🏛️','jade-gold',
    [{ name:'Mini Reserve Token',icon:'🏛️',rarity:'polished',qty:1,guaranteed:true },{ name:'Jade Dust',icon:'✨',rarity:'rough',qty:100,guaranteed:true }],
    { targetSegment:'new_spender', emotionalHook:'Your first reserve-backed piece', scores:{ visual_desirability:5,perceived_value:6,real_margin:6,beginner_friendliness:6,collector_appeal:3,whale_appeal:1,urgency_strength:2,prestige_strength:4,retention_contribution:5,overall_attractiveness:5 } }),
  pack('sp-10','Sovereign Vault Master','Complete sovereign access','sovereign_packs','imperial','absurd',10000,'🌟','cosmic',
    [{ name:'Singularity Jade Fragment',icon:'🌟',rarity:'singularity',qty:1,guaranteed:false },{ name:'Imperial Jade',icon:'💎',rarity:'imperial',qty:2,guaranteed:true },{ name:'Sovereign Jade',icon:'💎',rarity:'sovereign',qty:5,guaranteed:true },{ name:'Jade Dust',icon:'✨',rarity:'rough',qty:10000,guaranteed:true }],
    { priceUsd:199.99, isLimited:true, purchaseLimit:1, targetSegment:'ultra_whale', emotionalHook:'The ultimate sovereign statement', scores:{ visual_desirability:10,perceived_value:9,real_margin:8,beginner_friendliness:1,collector_appeal:10,whale_appeal:10,urgency_strength:7,prestige_strength:10,retention_contribution:5,overall_attractiveness:10 } }),

  // ────── ARTISAN TOOLS (10) ──────
  pack('at-01','Precision Chisel Kit','Master-grade tools','artisan_tools','refined','core',250,'⛏️','jade-green',
    [{ name:'Precision Chisel',icon:'⛏️',rarity:'refined',qty:1,guaranteed:true },{ name:'Calibration Stone',icon:'🪨',rarity:'polished',qty:2,guaranteed:true }],
    { targetSegment:'crafter', emotionalHook:'Cut with precision', scores:{ visual_desirability:6,perceived_value:7,real_margin:6,beginner_friendliness:5,collector_appeal:3,whale_appeal:2,urgency_strength:2,prestige_strength:4,retention_contribution:7,overall_attractiveness:6 } }),
  pack('at-02','Coolant Supply Pack','Keep the blade cool','artisan_tools','rough','micro',30,'🧪','jade-green',
    [{ name:'Coolant Flask',icon:'🧪',rarity:'rough',qty:5,guaranteed:true }],
    { targetSegment:'regular', emotionalHook:'Essential for every session', scores:{ visual_desirability:3,perceived_value:6,real_margin:8,beginner_friendliness:7,collector_appeal:1,whale_appeal:1,urgency_strength:3,prestige_strength:1,retention_contribution:6,overall_attractiveness:4 } }),
  pack('at-03','Polish Amplifier Set','Superior finish','artisan_tools','polished','core',180,'🧽','jade-green',
    [{ name:'Polish Amplifier',icon:'🧽',rarity:'polished',qty:3,guaranteed:true },{ name:'Luster Compound',icon:'✨',rarity:'polished',qty:2,guaranteed:true }],
    { targetSegment:'crafter', emotionalHook:'Mirror-finish jade', scores:{ visual_desirability:5,perceived_value:7,real_margin:6,beginner_friendliness:5,collector_appeal:3,whale_appeal:2,urgency_strength:2,prestige_strength:4,retention_contribution:6,overall_attractiveness:5 } }),
  pack('at-04','Master-Class Booster','Expert carving assist','artisan_tools','gilded','mid',450,'🎯','gold',
    [{ name:'Master-Class Token',icon:'🎯',rarity:'gilded',qty:1,guaranteed:true },{ name:'Precision Chisel',icon:'⛏️',rarity:'refined',qty:1,guaranteed:true }],
    { targetSegment:'advanced', emotionalHook:'Carve like a master', scores:{ visual_desirability:7,perceived_value:7,real_margin:6,beginner_friendliness:3,collector_appeal:4,whale_appeal:4,urgency_strength:3,prestige_strength:6,retention_contribution:6,overall_attractiveness:6 } }),
  pack('at-05','Lathe Calibration Kit','Perfect alignment','artisan_tools','refined','core',220,'⚙️','jade-green',
    [{ name:'Lathe Calibration Module',icon:'⚙️',rarity:'refined',qty:1,guaranteed:true },{ name:'Coolant Flask',icon:'🧪',rarity:'rough',qty:3,guaranteed:true }],
    { targetSegment:'crafter', emotionalHook:'Precision alignment for perfect cuts', scores:{ visual_desirability:5,perceived_value:7,real_margin:6,beginner_friendliness:4,collector_appeal:3,whale_appeal:2,urgency_strength:2,prestige_strength:4,retention_contribution:7,overall_attractiveness:5 } }),
  pack('at-06','Fracture Shield Pack','Protect your carving','artisan_tools','polished','core',150,'🛡️','jade-green',
    [{ name:'Fracture Shield',icon:'🛡️',rarity:'polished',qty:3,guaranteed:true }],
    { mostPopular:true, targetSegment:'all', emotionalHook:'Never lose a piece to bad luck', scores:{ visual_desirability:5,perceived_value:8,real_margin:6,beginner_friendliness:7,collector_appeal:2,whale_appeal:2,urgency_strength:4,prestige_strength:2,retention_contribution:9,overall_attractiveness:7 } }),
  pack('at-07','Tool Mastery Bundle','Complete artisan kit','artisan_tools','gilded','mid',600,'🧰','gold-jade',
    [{ name:'Precision Chisel',icon:'⛏️',rarity:'refined',qty:2,guaranteed:true },{ name:'Polish Amplifier',icon:'🧽',rarity:'polished',qty:3,guaranteed:true },{ name:'Coolant Flask',icon:'🧪',rarity:'rough',qty:5,guaranteed:true },{ name:'Fracture Shield',icon:'🛡️',rarity:'polished',qty:2,guaranteed:true }],
    { bestValue:true, targetSegment:'crafter', emotionalHook:'Every tool you need in one box', scores:{ visual_desirability:7,perceived_value:9,real_margin:4,beginner_friendliness:4,collector_appeal:3,whale_appeal:3,urgency_strength:3,prestige_strength:5,retention_contribution:8,overall_attractiveness:7 } }),
  pack('at-08','Diamond-Edge Upgrade','Ultimate cutting edge','artisan_tools','sovereign','elite',1000,'💎','platinum',
    [{ name:'Diamond-Edge Blade',icon:'💎',rarity:'sovereign',qty:1,guaranteed:true },{ name:'Master-Class Token',icon:'🎯',rarity:'gilded',qty:1,guaranteed:true }],
    { priceUsd:19.99, targetSegment:'whale_crafter', emotionalHook:'The finest blade in jade', scores:{ visual_desirability:9,perceived_value:8,real_margin:6,beginner_friendliness:1,collector_appeal:7,whale_appeal:7,urgency_strength:4,prestige_strength:9,retention_contribution:5,overall_attractiveness:7 } }),
  pack('at-09','Quick Polish Pack','Fast finish','artisan_tools','rough','micro',20,'🧴','jade-green',
    [{ name:'Quick Polish',icon:'🧴',rarity:'rough',qty:3,guaranteed:true }],
    { targetSegment:'impulse', emotionalHook:'Instant shine', scores:{ visual_desirability:3,perceived_value:5,real_margin:8,beginner_friendliness:8,collector_appeal:1,whale_appeal:1,urgency_strength:2,prestige_strength:1,retention_contribution:5,overall_attractiveness:4 } }),
  pack('at-10','Sovereign Tool Chest','Imperial-grade artisan tools','artisan_tools','imperial','whale',2200,'👑','royal-purple',
    [{ name:'Imperial Chisel',icon:'⛏️',rarity:'imperial',qty:1,guaranteed:true },{ name:'Diamond-Edge Blade',icon:'💎',rarity:'sovereign',qty:1,guaranteed:true },{ name:'Master-Class Token',icon:'🎯',rarity:'gilded',qty:3,guaranteed:true },{ name:'Fracture Shield',icon:'🛡️',rarity:'polished',qty:5,guaranteed:true }],
    { priceUsd:44.99, featured:true, targetSegment:'whale_crafter', emotionalHook:'Tools worthy of an emperor', scores:{ visual_desirability:10,perceived_value:8,real_margin:7,beginner_friendliness:1,collector_appeal:8,whale_appeal:9,urgency_strength:4,prestige_strength:10,retention_contribution:5,overall_attractiveness:8 } }),

  // ────── ATELIER ACCESS (6) ──────
  pack('aa-01','Extra Carving Session','One more go','atelier_access','rough','micro',35,'🎨','jade-green',
    [{ name:'Session Token',icon:'🎟️',rarity:'rough',qty:1,guaranteed:true }],
    { targetSegment:'regular', emotionalHook:'Just one more session', scores:{ visual_desirability:4,perceived_value:5,real_margin:8,beginner_friendliness:6,collector_appeal:1,whale_appeal:1,urgency_strength:3,prestige_strength:2,retention_contribution:7,overall_attractiveness:5 } }),
  pack('aa-02','Focus Mode Theme','Zen carving environment','atelier_access','polished','core',150,'🧘','jade-green',
    [{ name:'Focus Mode Theme',icon:'🧘',rarity:'polished',qty:1,guaranteed:true }],
    { targetSegment:'crafter', emotionalHook:'Enter the jade meditation', scores:{ visual_desirability:7,perceived_value:6,real_margin:7,beginner_friendliness:5,collector_appeal:4,whale_appeal:2,urgency_strength:2,prestige_strength:5,retention_contribution:6,overall_attractiveness:6 } }),
  pack('aa-03','Premium Studio Unlock','Elite workspace','atelier_access','gilded','mid',500,'🏠','gold',
    [{ name:'Premium Studio Key',icon:'🏠',rarity:'gilded',qty:1,guaranteed:true },{ name:'Session Token',icon:'🎟️',rarity:'rough',qty:5,guaranteed:true }],
    { targetSegment:'premium', emotionalHook:'Your private jade studio', scores:{ visual_desirability:8,perceived_value:7,real_margin:6,beginner_friendliness:3,collector_appeal:5,whale_appeal:5,urgency_strength:3,prestige_strength:7,retention_contribution:7,overall_attractiveness:7 } }),
  pack('aa-04','Elite Workshop Access','The finest atelier','atelier_access','sovereign','elite',1200,'🏰','royal-purple',
    [{ name:'Elite Workshop Pass',icon:'🏰',rarity:'sovereign',qty:1,guaranteed:true },{ name:'Premium Studio Key',icon:'🏠',rarity:'gilded',qty:1,guaranteed:true }],
    { priceUsd:24.99, targetSegment:'whale', emotionalHook:'Where sovereign jade is born', scores:{ visual_desirability:9,perceived_value:8,real_margin:6,beginner_friendliness:1,collector_appeal:7,whale_appeal:8,urgency_strength:4,prestige_strength:9,retention_contribution:6,overall_attractiveness:8 } }),
  pack('aa-05','High-Purity Pass','Access rare materials','atelier_access','gilded','mid',400,'🔬','jade-gold',
    [{ name:'High-Purity Eligibility Pass',icon:'🔬',rarity:'gilded',qty:1,guaranteed:true }],
    { isLimited:true, targetSegment:'collector', emotionalHook:'Access jade others cannot touch', scores:{ visual_desirability:7,perceived_value:7,real_margin:7,beginner_friendliness:2,collector_appeal:8,whale_appeal:5,urgency_strength:6,prestige_strength:8,retention_contribution:5,overall_attractiveness:7 } }),
  pack('aa-06','Session Bundle 10','Ten carving sessions','atelier_access','polished','core',280,'🎨','jade-green',
    [{ name:'Session Token',icon:'🎟️',rarity:'rough',qty:10,guaranteed:true },{ name:'Coolant Flask',icon:'🧪',rarity:'rough',qty:3,guaranteed:true }],
    { bestValue:true, targetSegment:'regular', emotionalHook:'Ten sessions, one price', scores:{ visual_desirability:5,perceived_value:8,real_margin:5,beginner_friendliness:5,collector_appeal:2,whale_appeal:2,urgency_strength:2,prestige_strength:2,retention_contribution:8,overall_attractiveness:6 } }),

  // ────── BLUEPRINT PACKS (6) ──────
  pack('bp-01','Blueprint Mint Pass','Create a design','blueprint_packs','refined','core',300,'📐','jade-green',
    [{ name:'Blueprint Mint Pass',icon:'📐',rarity:'refined',qty:1,guaranteed:true }],
    { targetSegment:'creator', emotionalHook:'Author a jade design', scores:{ visual_desirability:6,perceived_value:7,real_margin:6,beginner_friendliness:3,collector_appeal:6,whale_appeal:3,urgency_strength:2,prestige_strength:6,retention_contribution:6,overall_attractiveness:6 } }),
  pack('bp-02','Licensed Reproduction Slots','Reproduce jade designs','blueprint_packs','gilded','mid',500,'📋','gold',
    [{ name:'Reproduction License',icon:'📋',rarity:'gilded',qty:3,guaranteed:true }],
    { targetSegment:'creator', emotionalHook:'Monetize your creations', scores:{ visual_desirability:6,perceived_value:7,real_margin:7,beginner_friendliness:2,collector_appeal:5,whale_appeal:4,urgency_strength:3,prestige_strength:6,retention_contribution:6,overall_attractiveness:6 } }),
  pack('bp-03','Creator Royalty Boost','Enhanced royalties','blueprint_packs','sovereign','elite',1000,'💰','gold',
    [{ name:'Royalty Enhancement',icon:'💰',rarity:'sovereign',qty:1,guaranteed:true },{ name:'Blueprint Mint Pass',icon:'📐',rarity:'refined',qty:2,guaranteed:true }],
    { priceUsd:19.99, targetSegment:'top_creator', emotionalHook:'Earn more from every reproduction', scores:{ visual_desirability:7,perceived_value:8,real_margin:6,beginner_friendliness:1,collector_appeal:6,whale_appeal:6,urgency_strength:3,prestige_strength:7,retention_contribution:7,overall_attractiveness:7 } }),
  pack('bp-04','Premium Registry Pack','Register premium blueprints','blueprint_packs','gilded','mid',450,'🏛️','jade-gold',
    [{ name:'Premium Registry Slot',icon:'🏛️',rarity:'gilded',qty:2,guaranteed:true }],
    { targetSegment:'creator', emotionalHook:'Premium visibility for your designs', scores:{ visual_desirability:6,perceived_value:6,real_margin:7,beginner_friendliness:2,collector_appeal:5,whale_appeal:3,urgency_strength:2,prestige_strength:6,retention_contribution:5,overall_attractiveness:5 } }),
  pack('bp-05','Starter Blueprint Kit','Begin creating','blueprint_packs','polished','entry',120,'📝','jade-green',
    [{ name:'Basic Blueprint Pass',icon:'📝',rarity:'polished',qty:1,guaranteed:true },{ name:'Jade Dust',icon:'✨',rarity:'rough',qty:100,guaranteed:true }],
    { targetSegment:'new_creator', emotionalHook:'Start designing jade', scores:{ visual_desirability:5,perceived_value:7,real_margin:5,beginner_friendliness:7,collector_appeal:3,whale_appeal:1,urgency_strength:2,prestige_strength:3,retention_contribution:6,overall_attractiveness:5 } }),
  pack('bp-06','Master Blueprint Vault','Full creator suite','blueprint_packs','imperial','whale',2500,'👑','royal-purple',
    [{ name:'Imperial Blueprint Pass',icon:'👑',rarity:'imperial',qty:1,guaranteed:true },{ name:'Reproduction License',icon:'📋',rarity:'gilded',qty:10,guaranteed:true },{ name:'Royalty Enhancement',icon:'💰',rarity:'sovereign',qty:1,guaranteed:true }],
    { priceUsd:49.99, featured:true, targetSegment:'whale_creator', emotionalHook:'The ultimate creator arsenal', scores:{ visual_desirability:9,perceived_value:8,real_margin:7,beginner_friendliness:1,collector_appeal:8,whale_appeal:9,urgency_strength:4,prestige_strength:9,retention_contribution:6,overall_attractiveness:8 } }),

  // ────── PRESTIGE COSMETICS (8) ──────
  pack('pc-01','Sovereign Gold UI Theme','Gold interface overlay','prestige_cosmetics','gilded','mid',400,'🎨','gold',
    [{ name:'Sovereign Gold Theme',icon:'🎨',rarity:'gilded',qty:1,guaranteed:true }],
    { targetSegment:'prestige', emotionalHook:'Bathe your interface in gold', scores:{ visual_desirability:9,perceived_value:6,real_margin:8,beginner_friendliness:4,collector_appeal:7,whale_appeal:5,urgency_strength:2,prestige_strength:8,retention_contribution:5,overall_attractiveness:7 } }),
  pack('pc-02','Dynasty Atelier Skin','Royal workshop theme','prestige_cosmetics','sovereign','elite',800,'👑','royal-purple',
    [{ name:'Dynasty Atelier Skin',icon:'👑',rarity:'sovereign',qty:1,guaranteed:true }],
    { priceUsd:14.99, targetSegment:'prestige', emotionalHook:'Carve in a dynasty\'s workshop', scores:{ visual_desirability:9,perceived_value:6,real_margin:8,beginner_friendliness:2,collector_appeal:8,whale_appeal:6,urgency_strength:3,prestige_strength:9,retention_contribution:5,overall_attractiveness:7 } }),
  pack('pc-03','Signature Engraving Pack','Custom jade marks','prestige_cosmetics','refined','core',250,'✍️','jade-gold',
    [{ name:'Signature Engraving Style',icon:'✍️',rarity:'refined',qty:3,guaranteed:true }],
    { targetSegment:'crafter', emotionalHook:'Leave your mark on every piece', scores:{ visual_desirability:7,perceived_value:6,real_margin:7,beginner_friendliness:4,collector_appeal:6,whale_appeal:3,urgency_strength:2,prestige_strength:7,retention_contribution:5,overall_attractiveness:6 } }),
  pack('pc-04','Vault Cinematic Pack','Epic opening animations','prestige_cosmetics','gilded','mid',500,'🎬','gold',
    [{ name:'Vault Opening Cinematic',icon:'🎬',rarity:'gilded',qty:2,guaranteed:true }],
    { targetSegment:'prestige', emotionalHook:'Every vault opening becomes epic', scores:{ visual_desirability:9,perceived_value:5,real_margin:9,beginner_friendliness:3,collector_appeal:6,whale_appeal:4,urgency_strength:3,prestige_strength:7,retention_contribution:4,overall_attractiveness:6 } }),
  pack('pc-05','Luster Aura Effect','Glowing jade effects','prestige_cosmetics','refined','core',180,'✨','jade-green',
    [{ name:'Luster Aura',icon:'✨',rarity:'refined',qty:1,guaranteed:true }],
    { targetSegment:'all', emotionalHook:'Your jade glows differently', scores:{ visual_desirability:8,perceived_value:5,real_margin:8,beginner_friendliness:5,collector_appeal:5,whale_appeal:3,urgency_strength:2,prestige_strength:6,retention_contribution:4,overall_attractiveness:6 } }),
  pack('pc-06','Collector Frame Set','Display frames for jade','prestige_cosmetics','polished','core',150,'🖼️','jade-green',
    [{ name:'Collector Display Frame',icon:'🖼️',rarity:'polished',qty:5,guaranteed:true }],
    { targetSegment:'collector', emotionalHook:'Frame your finest pieces', scores:{ visual_desirability:6,perceived_value:6,real_margin:7,beginner_friendliness:5,collector_appeal:8,whale_appeal:2,urgency_strength:2,prestige_strength:5,retention_contribution:5,overall_attractiveness:5 } }),
  pack('pc-07','Profile Emblem Pack','Status emblems','prestige_cosmetics','gilded','mid',350,'🏅','gold',
    [{ name:'Profile Emblem',icon:'🏅',rarity:'gilded',qty:3,guaranteed:true }],
    { targetSegment:'prestige', emotionalHook:'Show your rank', scores:{ visual_desirability:7,perceived_value:5,real_margin:8,beginner_friendliness:4,collector_appeal:6,whale_appeal:4,urgency_strength:2,prestige_strength:7,retention_contribution:4,overall_attractiveness:6 } }),
  pack('pc-08','Imperial Cosmetic Suite','Complete prestige overhaul','prestige_cosmetics','imperial','whale',2000,'🌟','cosmic',
    [{ name:'Imperial UI Theme',icon:'🎨',rarity:'imperial',qty:1,guaranteed:true },{ name:'Dynasty Atelier Skin',icon:'👑',rarity:'sovereign',qty:1,guaranteed:true },{ name:'Vault Cinematic',icon:'🎬',rarity:'gilded',qty:3,guaranteed:true },{ name:'Luster Aura',icon:'✨',rarity:'refined',qty:1,guaranteed:true },{ name:'Profile Emblem',icon:'🏅',rarity:'gilded',qty:5,guaranteed:true }],
    { priceUsd:39.99, featured:true, targetSegment:'whale', emotionalHook:'Total prestige transformation', scores:{ visual_desirability:10,perceived_value:8,real_margin:7,beginner_friendliness:1,collector_appeal:9,whale_appeal:9,urgency_strength:4,prestige_strength:10,retention_contribution:5,overall_attractiveness:9 } }),

  // ────── FRACTIONAL OWNERSHIP (6) ──────
  pack('fo-01','Fractional Entry Bundle','Own a piece of elite jade','fractional_ownership','refined','core',200,'📊','jade-gold',
    [{ name:'Fractional Share Token',icon:'📊',rarity:'refined',qty:5,guaranteed:true }],
    { targetSegment:'investor', emotionalHook:'Own a piece of something great', scores:{ visual_desirability:6,perceived_value:7,real_margin:6,beginner_friendliness:4,collector_appeal:6,whale_appeal:3,urgency_strength:3,prestige_strength:5,retention_contribution:6,overall_attractiveness:6 } }),
  pack('fo-02','Curated Share Basket','Diversified jade exposure','fractional_ownership','gilded','mid',600,'🧺','gold',
    [{ name:'Curated Share Basket',icon:'🧺',rarity:'gilded',qty:1,guaranteed:true }],
    { targetSegment:'investor', emotionalHook:'Diversified jade portfolio', scores:{ visual_desirability:7,perceived_value:7,real_margin:6,beginner_friendliness:3,collector_appeal:6,whale_appeal:5,urgency_strength:3,prestige_strength:6,retention_contribution:6,overall_attractiveness:6 } }),
  pack('fo-03','Collector Exposure Pack','Elite jade shares','fractional_ownership','sovereign','elite',1500,'🏛️','royal-purple',
    [{ name:'Elite Share Basket',icon:'🏛️',rarity:'sovereign',qty:1,guaranteed:true },{ name:'Fractional Share Token',icon:'📊',rarity:'refined',qty:10,guaranteed:true }],
    { priceUsd:29.99, targetSegment:'investor', emotionalHook:'Access the top tier', scores:{ visual_desirability:8,perceived_value:8,real_margin:6,beginner_friendliness:2,collector_appeal:8,whale_appeal:7,urgency_strength:4,prestige_strength:8,retention_contribution:5,overall_attractiveness:7 } }),
  pack('fo-04','Premium Buyout Pass','Right to buy full piece','fractional_ownership','imperial','whale',3000,'🔐','cosmic',
    [{ name:'Buyout Right Pass',icon:'🔐',rarity:'imperial',qty:1,guaranteed:true }],
    { priceUsd:59.99, isLimited:true, targetSegment:'whale', emotionalHook:'Convert shares to ownership', scores:{ visual_desirability:8,perceived_value:8,real_margin:7,beginner_friendliness:1,collector_appeal:9,whale_appeal:10,urgency_strength:6,prestige_strength:9,retention_contribution:4,overall_attractiveness:8 } }),
  pack('fo-05','Micro Share Pack','Tiny jade exposure','fractional_ownership','rough','micro',30,'📊','jade-green',
    [{ name:'Micro Share Token',icon:'📊',rarity:'rough',qty:1,guaranteed:true }],
    { targetSegment:'casual', emotionalHook:'Even a small share matters', scores:{ visual_desirability:3,perceived_value:5,real_margin:7,beginner_friendliness:7,collector_appeal:3,whale_appeal:1,urgency_strength:2,prestige_strength:2,retention_contribution:4,overall_attractiveness:4 } }),
  pack('fo-06','Share Accumulator','Build your portfolio','fractional_ownership','polished','core',150,'📈','jade-green',
    [{ name:'Fractional Share Token',icon:'📊',rarity:'polished',qty:3,guaranteed:true }],
    { targetSegment:'regular', emotionalHook:'Steady jade accumulation', scores:{ visual_desirability:4,perceived_value:6,real_margin:6,beginner_friendliness:5,collector_appeal:4,whale_appeal:2,urgency_strength:2,prestige_strength:3,retention_contribution:6,overall_attractiveness:5 } }),

  // ────── EVENT PACKS (12) ──────
  pack('ep-01','Lunar New Year Jade','Festival prosperity jade','event_packs','gilded','mid',450,'🧧','red-gold',
    [{ name:'Lunar Jade Block',icon:'🧧',rarity:'gilded',qty:1,guaranteed:true },{ name:'Red Envelope Dust',icon:'✨',rarity:'refined',qty:200,guaranteed:true }],
    { rotationType:'seasonal', seasonal:'lunar_new_year', isLimited:true, availabilityHours:336, targetSegment:'all', emotionalHook:'Prosperity in jade form', scores:{ visual_desirability:9,perceived_value:8,real_margin:5,beginner_friendliness:5,collector_appeal:8,whale_appeal:5,urgency_strength:9,prestige_strength:7,retention_contribution:7,overall_attractiveness:8 } }),
  pack('ep-02','Sovereign Eclipse Vault','Once-a-year event','event_packs','sovereign','elite',1500,'🌑','cosmic',
    [{ name:'Eclipse Sovereign Jade',icon:'🌑',rarity:'sovereign',qty:1,guaranteed:true },{ name:'Eclipse Dust',icon:'✨',rarity:'gilded',qty:500,guaranteed:true }],
    { priceUsd:29.99, rotationType:'seasonal', isLimited:true, availabilityHours:72, targetSegment:'collector', emotionalHook:'The eclipse reveals sovereign jade', scores:{ visual_desirability:10,perceived_value:9,real_margin:6,beginner_friendliness:2,collector_appeal:10,whale_appeal:8,urgency_strength:10,prestige_strength:10,retention_contribution:6,overall_attractiveness:9 } }),
  pack('ep-03','Gold Storm Pack','Market rally celebration','event_packs','gilded','mid',500,'⛈️','gold',
    [{ name:'Storm Gold Jade',icon:'⛈️',rarity:'gilded',qty:2,guaranteed:true }],
    { rotationType:'event', isLimited:true, availabilityHours:48, targetSegment:'all', emotionalHook:'Ride the golden storm', scores:{ visual_desirability:8,perceived_value:7,real_margin:6,beginner_friendliness:4,collector_appeal:7,whale_appeal:5,urgency_strength:9,prestige_strength:6,retention_contribution:6,overall_attractiveness:7 } }),
  pack('ep-04','Dynasty Festival Offer','Cultural celebration','event_packs','refined','core',300,'🎪','red-gold',
    [{ name:'Festival Jade Ornament',icon:'🎪',rarity:'refined',qty:2,guaranteed:true },{ name:'Jade Dust',icon:'✨',rarity:'rough',qty:150,guaranteed:true }],
    { rotationType:'seasonal', seasonal:'dynasty_festival', isLimited:true, targetSegment:'all', emotionalHook:'Celebrate with jade', scores:{ visual_desirability:7,perceived_value:7,real_margin:5,beginner_friendliness:6,collector_appeal:6,whale_appeal:3,urgency_strength:7,prestige_strength:5,retention_contribution:6,overall_attractiveness:6 } }),
  pack('ep-05','Flash Prestige Offer','4-hour flash sale','event_packs','sovereign','elite',1000,'⚡','gold',
    [{ name:'Flash Sovereign Shard',icon:'⚡',rarity:'sovereign',qty:1,guaranteed:true }],
    { priceUsd:19.99, rotationType:'flash', isLimited:true, availabilityHours:4, targetSegment:'impulse_whale', emotionalHook:'4 hours. One chance.', scores:{ visual_desirability:9,perceived_value:8,real_margin:7,beginner_friendliness:1,collector_appeal:8,whale_appeal:8,urgency_strength:10,prestige_strength:9,retention_contribution:5,overall_attractiveness:8 } }),
  pack('ep-06','Market Heat Pack','When markets surge','event_packs','refined','core',250,'🔥','red-gold',
    [{ name:'Heat-Forged Shard',icon:'🔥',rarity:'refined',qty:2,guaranteed:true }],
    { rotationType:'event', isLimited:true, targetSegment:'all', emotionalHook:'Forged in market heat', scores:{ visual_desirability:7,perceived_value:6,real_margin:6,beginner_friendliness:5,collector_appeal:5,whale_appeal:3,urgency_strength:7,prestige_strength:5,retention_contribution:5,overall_attractiveness:6 } }),
  pack('ep-07','Cherry Blossom Jade','Spring seasonal','event_packs','gilded','mid',400,'🌸','pink-gold',
    [{ name:'Blossom Jade',icon:'🌸',rarity:'gilded',qty:1,guaranteed:true },{ name:'Spring Dust',icon:'🌿',rarity:'refined',qty:150,guaranteed:true }],
    { rotationType:'seasonal', seasonal:'spring', isLimited:true, targetSegment:'collector', emotionalHook:'Jade blooms in spring', scores:{ visual_desirability:9,perceived_value:7,real_margin:6,beginner_friendliness:4,collector_appeal:9,whale_appeal:5,urgency_strength:8,prestige_strength:7,retention_contribution:6,overall_attractiveness:7 } }),
  pack('ep-08','Winter Solstice Vault','Darkest night, brightest jade','event_packs','sovereign','elite',1200,'❄️','ice-blue',
    [{ name:'Solstice Sovereign Jade',icon:'❄️',rarity:'sovereign',qty:1,guaranteed:true },{ name:'Frost Dust',icon:'✨',rarity:'gilded',qty:300,guaranteed:true }],
    { priceUsd:24.99, rotationType:'seasonal', seasonal:'winter', isLimited:true, availabilityHours:168, targetSegment:'collector', emotionalHook:'Born from the longest night', scores:{ visual_desirability:10,perceived_value:8,real_margin:6,beginner_friendliness:2,collector_appeal:9,whale_appeal:7,urgency_strength:9,prestige_strength:9,retention_contribution:6,overall_attractiveness:8 } }),
  pack('ep-09','Harvest Moon Pack','Autumn bounty','event_packs','refined','core',280,'🌕','gold',
    [{ name:'Harvest Jade',icon:'🌕',rarity:'refined',qty:2,guaranteed:true },{ name:'Jade Dust',icon:'✨',rarity:'rough',qty:200,guaranteed:true }],
    { rotationType:'seasonal', seasonal:'autumn', isLimited:true, targetSegment:'all', emotionalHook:'Harvest the moon\'s jade', scores:{ visual_desirability:7,perceived_value:7,real_margin:5,beginner_friendliness:5,collector_appeal:6,whale_appeal:3,urgency_strength:7,prestige_strength:5,retention_contribution:6,overall_attractiveness:6 } }),
  pack('ep-10','Anniversary Celebration','Platform birthday','event_packs','imperial','whale',2000,'🎂','cosmic',
    [{ name:'Anniversary Imperial Jade',icon:'🎂',rarity:'imperial',qty:1,guaranteed:true },{ name:'Anniversary Emblem',icon:'🏅',rarity:'sovereign',qty:1,guaranteed:true },{ name:'Jade Dust',icon:'✨',rarity:'rough',qty:1000,guaranteed:true }],
    { priceUsd:39.99, rotationType:'event', isLimited:true, purchaseLimit:1, targetSegment:'all', emotionalHook:'Only on our birthday', scores:{ visual_desirability:10,perceived_value:9,real_margin:6,beginner_friendliness:3,collector_appeal:10,whale_appeal:8,urgency_strength:10,prestige_strength:9,retention_contribution:7,overall_attractiveness:9 } }),
  pack('ep-11','Midnight Flash','Midnight-only offer','event_packs','gilded','mid',350,'🌙','cosmic',
    [{ name:'Midnight Jade',icon:'🌙',rarity:'gilded',qty:1,guaranteed:true }],
    { rotationType:'flash', isLimited:true, availabilityHours:2, targetSegment:'night_owl', emotionalHook:'Only between midnight and 2AM', scores:{ visual_desirability:8,perceived_value:6,real_margin:7,beginner_friendliness:3,collector_appeal:7,whale_appeal:4,urgency_strength:10,prestige_strength:6,retention_contribution:4,overall_attractiveness:7 } }),
  pack('ep-12','Dragon Boat Jade','Festival special','event_packs','refined','core',320,'🐉','jade-gold',
    [{ name:'Dragon Jade',icon:'🐉',rarity:'refined',qty:1,guaranteed:true },{ name:'Dragon Scale Dust',icon:'✨',rarity:'polished',qty:100,guaranteed:true }],
    { rotationType:'seasonal', seasonal:'dragon_boat', isLimited:true, targetSegment:'all', emotionalHook:'Dragon spirit in jade', scores:{ visual_desirability:8,perceived_value:7,real_margin:5,beginner_friendliness:5,collector_appeal:7,whale_appeal:3,urgency_strength:8,prestige_strength:6,retention_contribution:6,overall_attractiveness:7 } }),

  // ────── UTILITY / RECOVERY (10) ──────
  pack('ut-01','Fracture Recovery Pack','Heal after fracture','utility_packs','polished','core',150,'🩹','jade-green',
    [{ name:'Fracture Recovery Kit',icon:'🩹',rarity:'polished',qty:2,guaranteed:true },{ name:'Coolant Flask',icon:'🧪',rarity:'rough',qty:3,guaranteed:true }],
    { mostPopular:true, targetSegment:'after_loss', emotionalHook:'Don\'t let a fracture end your session', scores:{ visual_desirability:5,perceived_value:8,real_margin:6,beginner_friendliness:7,collector_appeal:2,whale_appeal:2,urgency_strength:7,prestige_strength:2,retention_contribution:9,overall_attractiveness:7 } }),
  pack('ut-02','Salvage Booster Pack','Recover lost value','utility_packs','refined','core',200,'🔄','jade-green',
    [{ name:'Salvage Booster',icon:'🔄',rarity:'refined',qty:2,guaranteed:true }],
    { targetSegment:'after_loss', emotionalHook:'Salvage what you can', scores:{ visual_desirability:5,perceived_value:7,real_margin:6,beginner_friendliness:5,collector_appeal:2,whale_appeal:2,urgency_strength:6,prestige_strength:2,retention_contribution:8,overall_attractiveness:6 } }),
  pack('ut-03','Coolant Refill Bundle','Stay cool','utility_packs','rough','micro',40,'🧪','jade-green',
    [{ name:'Coolant Flask',icon:'🧪',rarity:'rough',qty:8,guaranteed:true }],
    { targetSegment:'regular', emotionalHook:'Never run dry', scores:{ visual_desirability:3,perceived_value:7,real_margin:7,beginner_friendliness:7,collector_appeal:1,whale_appeal:1,urgency_strength:3,prestige_strength:1,retention_contribution:7,overall_attractiveness:5 } }),
  pack('ut-04','Precision Retry Pack','Second chance','utility_packs','polished','core',120,'🔁','jade-green',
    [{ name:'Retry Token',icon:'🔁',rarity:'polished',qty:2,guaranteed:true }],
    { targetSegment:'after_loss', emotionalHook:'Every artisan deserves a second try', scores:{ visual_desirability:5,perceived_value:7,real_margin:6,beginner_friendliness:6,collector_appeal:2,whale_appeal:2,urgency_strength:5,prestige_strength:2,retention_contribution:8,overall_attractiveness:6 } }),
  pack('ut-05','Workshop Reset Kit','Fresh start','utility_packs','rough','micro',50,'🔧','jade-green',
    [{ name:'Workshop Reset Token',icon:'🔧',rarity:'rough',qty:1,guaranteed:true }],
    { targetSegment:'frustrated', emotionalHook:'Start the session fresh', scores:{ visual_desirability:3,perceived_value:5,real_margin:8,beginner_friendliness:7,collector_appeal:1,whale_appeal:1,urgency_strength:4,prestige_strength:1,retention_contribution:7,overall_attractiveness:4 } }),
  pack('ut-06','Emergency Fracture Shield','Instant protection','utility_packs','refined','core',250,'🛡️','jade-gold',
    [{ name:'Emergency Fracture Shield',icon:'🛡️',rarity:'refined',qty:3,guaranteed:true }],
    { targetSegment:'cautious', emotionalHook:'Insurance for your finest jade', scores:{ visual_desirability:6,perceived_value:8,real_margin:6,beginner_friendliness:5,collector_appeal:3,whale_appeal:3,urgency_strength:5,prestige_strength:3,retention_contribution:8,overall_attractiveness:6 } }),
  pack('ut-07','Jade First Aid','Micro recovery','utility_packs','rough','micro',20,'💊','jade-green',
    [{ name:'Jade Repair Paste',icon:'💊',rarity:'rough',qty:3,guaranteed:true }],
    { targetSegment:'all', emotionalHook:'Quick fix', scores:{ visual_desirability:3,perceived_value:5,real_margin:8,beginner_friendliness:8,collector_appeal:1,whale_appeal:1,urgency_strength:3,prestige_strength:1,retention_contribution:5,overall_attractiveness:4 } }),
  pack('ut-08','Full Session Recovery','Complete session reset','utility_packs','gilded','mid',400,'♻️','gold',
    [{ name:'Full Recovery Token',icon:'♻️',rarity:'gilded',qty:1,guaranteed:true },{ name:'Coolant Flask',icon:'🧪',rarity:'rough',qty:5,guaranteed:true },{ name:'Fracture Shield',icon:'🛡️',rarity:'polished',qty:2,guaranteed:true }],
    { bestValue:true, targetSegment:'after_loss', emotionalHook:'Complete recovery after disaster', scores:{ visual_desirability:7,perceived_value:9,real_margin:5,beginner_friendliness:4,collector_appeal:2,whale_appeal:3,urgency_strength:7,prestige_strength:3,retention_contribution:9,overall_attractiveness:7 } }),
  pack('ut-09','Pity Boost Token','Accelerate pity meter','utility_packs','refined','core',300,'📈','jade-gold',
    [{ name:'Pity Boost Token',icon:'📈',rarity:'refined',qty:1,guaranteed:true }],
    { targetSegment:'unlucky', emotionalHook:'+10 pity progress instantly', scores:{ visual_desirability:6,perceived_value:7,real_margin:7,beginner_friendliness:3,collector_appeal:4,whale_appeal:4,urgency_strength:4,prestige_strength:3,retention_contribution:7,overall_attractiveness:6 } }),
  pack('ut-10','Lucky Charm Bundle','Improve your odds','utility_packs','polished','core',180,'🍀','jade-green',
    [{ name:'Lucky Charm',icon:'🍀',rarity:'polished',qty:3,guaranteed:true }],
    { targetSegment:'superstitious', emotionalHook:'Feel the luck flow', scores:{ visual_desirability:6,perceived_value:5,real_margin:8,beginner_friendliness:6,collector_appeal:3,whale_appeal:2,urgency_strength:3,prestige_strength:3,retention_contribution:5,overall_attractiveness:5 } }),

  // ────── WHALE / COLLECTOR RESERVE (12) ──────
  pack('wh-01','Imperial Vault Access','The emperor\'s vault','whale_packs','imperial','whale',5000,'🏯','cosmic',
    [{ name:'Imperial Jade Block',icon:'💎',rarity:'imperial',qty:2,guaranteed:true },{ name:'Sovereign Jade',icon:'💎',rarity:'sovereign',qty:3,guaranteed:true },{ name:'Jade Dust',icon:'✨',rarity:'rough',qty:5000,guaranteed:true }],
    { priceUsd:99.99, featured:true, targetSegment:'whale', emotionalHook:'Walk into the emperor\'s vault', scores:{ visual_desirability:10,perceived_value:9,real_margin:7,beginner_friendliness:1,collector_appeal:10,whale_appeal:10,urgency_strength:5,prestige_strength:10,retention_contribution:5,overall_attractiveness:9 } }),
  pack('wh-02','Monolith Class Reserve','Monolithic jade piece','whale_packs','singularity','absurd',20000,'🗿','cosmic',
    [{ name:'Monolith Jade',icon:'🗿',rarity:'singularity',qty:1,guaranteed:true },{ name:'Imperial Jade',icon:'💎',rarity:'imperial',qty:3,guaranteed:true },{ name:'Jade Dust',icon:'✨',rarity:'rough',qty:20000,guaranteed:true }],
    { priceUsd:499.99, isLimited:true, purchaseLimit:1, targetSegment:'ultra_whale', emotionalHook:'The monolith stands alone', scores:{ visual_desirability:10,perceived_value:8,real_margin:9,beginner_friendliness:1,collector_appeal:10,whale_appeal:10,urgency_strength:7,prestige_strength:10,retention_contribution:4,overall_attractiveness:9 } }),
  pack('wh-03','Dynasty Founder Pack','Found your jade dynasty','whale_packs','imperial','whale',7500,'👑','royal-purple',
    [{ name:'Dynasty Founder Seal',icon:'👑',rarity:'imperial',qty:1,guaranteed:true },{ name:'Imperial Jade',icon:'💎',rarity:'imperial',qty:1,guaranteed:true },{ name:'Sovereign Jade',icon:'💎',rarity:'sovereign',qty:5,guaranteed:true },{ name:'Blueprint Master Pass',icon:'📐',rarity:'sovereign',qty:1,guaranteed:true }],
    { priceUsd:149.99, purchaseLimit:1, targetSegment:'whale', emotionalHook:'Your dynasty begins today', scores:{ visual_desirability:10,perceived_value:9,real_margin:7,beginner_friendliness:1,collector_appeal:10,whale_appeal:10,urgency_strength:5,prestige_strength:10,retention_contribution:6,overall_attractiveness:9 } }),
  pack('wh-04','Sovereign Legend Pack','Legendary sovereign status','whale_packs','sovereign','whale',3500,'🌟','gold',
    [{ name:'Sovereign Legend Jade',icon:'🌟',rarity:'sovereign',qty:2,guaranteed:true },{ name:'Gilded Jade',icon:'💎',rarity:'gilded',qty:5,guaranteed:true },{ name:'Jade Dust',icon:'✨',rarity:'rough',qty:3000,guaranteed:true }],
    { priceUsd:69.99, targetSegment:'whale', emotionalHook:'Legend status achieved', scores:{ visual_desirability:9,perceived_value:8,real_margin:7,beginner_friendliness:1,collector_appeal:9,whale_appeal:9,urgency_strength:4,prestige_strength:9,retention_contribution:5,overall_attractiveness:8 } }),
  pack('wh-05','Eternal Signature Collection','Permanent signature jade','whale_packs','imperial','absurd',12000,'✍️','cosmic',
    [{ name:'Eternal Signature Jade',icon:'✍️',rarity:'imperial',qty:1,guaranteed:true },{ name:'Permanent Lineage Seal',icon:'🔏',rarity:'imperial',qty:1,guaranteed:true },{ name:'Sovereign Jade',icon:'💎',rarity:'sovereign',qty:3,guaranteed:true }],
    { priceUsd:249.99, isLimited:true, purchaseLimit:1, targetSegment:'ultra_whale', emotionalHook:'A signature that lasts forever', scores:{ visual_desirability:10,perceived_value:9,real_margin:8,beginner_friendliness:1,collector_appeal:10,whale_appeal:10,urgency_strength:6,prestige_strength:10,retention_contribution:4,overall_attractiveness:9 } }),
  pack('wh-06','Museum Tier Pack','Museum-grade jade collection','whale_packs','singularity','absurd',30000,'🏛️','cosmic',
    [{ name:'Museum-Grade Jade',icon:'🏛️',rarity:'singularity',qty:1,guaranteed:true },{ name:'Imperial Jade',icon:'💎',rarity:'imperial',qty:5,guaranteed:true },{ name:'Sovereign Jade',icon:'💎',rarity:'sovereign',qty:10,guaranteed:true },{ name:'Jade Dust',icon:'✨',rarity:'rough',qty:50000,guaranteed:true }],
    { priceUsd:999.99, isLimited:true, purchaseLimit:1, targetSegment:'ultra_whale', emotionalHook:'Your jade belongs in a museum', scores:{ visual_desirability:10,perceived_value:9,real_margin:9,beginner_friendliness:1,collector_appeal:10,whale_appeal:10,urgency_strength:7,prestige_strength:10,retention_contribution:3,overall_attractiveness:10 } }),
  pack('wh-07','Emperor\'s Jade Treasury','The ultimate collection','whale_packs','singularity','absurd',50000,'🐉','cosmic',
    [{ name:'Emperor\'s Jade',icon:'🐉',rarity:'singularity',qty:2,guaranteed:true },{ name:'Imperial Jade',icon:'💎',rarity:'imperial',qty:10,guaranteed:true },{ name:'Complete Cosmetic Suite',icon:'✨',rarity:'imperial',qty:1,guaranteed:true },{ name:'Jade Dust',icon:'✨',rarity:'rough',qty:100000,guaranteed:true }],
    { priceUsd:1999.99, isLimited:true, purchaseLimit:1, targetSegment:'ultra_whale', emotionalHook:'You ARE the jade economy', scores:{ visual_desirability:10,perceived_value:10,real_margin:9,beginner_friendliness:1,collector_appeal:10,whale_appeal:10,urgency_strength:8,prestige_strength:10,retention_contribution:3,overall_attractiveness:10 } }),
  pack('wh-08','Black Vault Sovereign','Darkened vault secrets','whale_packs','imperial','whale',6000,'🖤','cosmic',
    [{ name:'Black Vault Jade',icon:'🖤',rarity:'imperial',qty:1,guaranteed:true },{ name:'Void Jade Dust',icon:'✨',rarity:'sovereign',qty:1000,guaranteed:true }],
    { priceUsd:119.99, isLimited:true, targetSegment:'whale', emotionalHook:'From the darkest vault', scores:{ visual_desirability:10,perceived_value:8,real_margin:8,beginner_friendliness:1,collector_appeal:9,whale_appeal:9,urgency_strength:6,prestige_strength:10,retention_contribution:4,overall_attractiveness:9 } }),
  pack('wh-09','Celestial Monolith','Star-forged jade','whale_packs','singularity','absurd',25000,'🌌','cosmic',
    [{ name:'Celestial Jade',icon:'🌌',rarity:'singularity',qty:1,guaranteed:true },{ name:'Star Dust',icon:'✨',rarity:'imperial',qty:5000,guaranteed:true }],
    { priceUsd:599.99, isLimited:true, purchaseLimit:1, targetSegment:'ultra_whale', emotionalHook:'Forged in the stars', scores:{ visual_desirability:10,perceived_value:9,real_margin:9,beginner_friendliness:1,collector_appeal:10,whale_appeal:10,urgency_strength:7,prestige_strength:10,retention_contribution:3,overall_attractiveness:10 } }),
  pack('wh-10','Jade Ascendant Pack','Rise above all','whale_packs','sovereign','whale',4000,'🏔️','royal-purple',
    [{ name:'Ascendant Jade',icon:'🏔️',rarity:'sovereign',qty:3,guaranteed:true },{ name:'Gilded Jade',icon:'💎',rarity:'gilded',qty:8,guaranteed:true },{ name:'Jade Dust',icon:'✨',rarity:'rough',qty:4000,guaranteed:true }],
    { priceUsd:79.99, targetSegment:'whale', emotionalHook:'Ascend to jade mastery', scores:{ visual_desirability:9,perceived_value:8,real_margin:7,beginner_friendliness:1,collector_appeal:9,whale_appeal:9,urgency_strength:4,prestige_strength:9,retention_contribution:5,overall_attractiveness:8 } }),
  pack('wh-11','Relic Curator Pack','Ancient jade relics','whale_packs','imperial','whale',5500,'🏺','cosmic',
    [{ name:'Ancient Jade Relic',icon:'🏺',rarity:'imperial',qty:1,guaranteed:true },{ name:'Relic Authentication Seal',icon:'🔏',rarity:'sovereign',qty:1,guaranteed:true },{ name:'Sovereign Jade',icon:'💎',rarity:'sovereign',qty:3,guaranteed:true }],
    { priceUsd:109.99, isLimited:true, targetSegment:'collector_whale', emotionalHook:'Curate ancient jade', scores:{ visual_desirability:10,perceived_value:8,real_margin:7,beginner_friendliness:1,collector_appeal:10,whale_appeal:9,urgency_strength:6,prestige_strength:10,retention_contribution:4,overall_attractiveness:9 } }),
  pack('wh-12','Jade Crown Reserve','The crown jewel','whale_packs','imperial','whale',8000,'👑','cosmic',
    [{ name:'Jade Crown',icon:'👑',rarity:'imperial',qty:1,guaranteed:true },{ name:'Crown Jewel Dust',icon:'✨',rarity:'sovereign',qty:3000,guaranteed:true },{ name:'Imperial Jade',icon:'💎',rarity:'imperial',qty:2,guaranteed:true }],
    { priceUsd:159.99, isLimited:true, purchaseLimit:1, targetSegment:'ultra_whale', emotionalHook:'Wear the jade crown', scores:{ visual_desirability:10,perceived_value:9,real_margin:8,beginner_friendliness:1,collector_appeal:10,whale_appeal:10,urgency_strength:6,prestige_strength:10,retention_contribution:4,overall_attractiveness:9 } }),

  // ────── SUBSCRIPTION / PASSES (10) ──────
  pack('su-01','Sovereign Pass','Monthly premium pass','subscription_passes','sovereign','mid',500,'🎫','gold',
    [{ name:'Sovereign Pass (30 days)',icon:'🎫',rarity:'sovereign',qty:1,guaranteed:true },{ name:'Daily Jade Drop',icon:'💎',rarity:'polished',qty:30,guaranteed:true },{ name:'Weekly Vault Key',icon:'🗝️',rarity:'refined',qty:4,guaranteed:true }],
    { priceUsd:9.99, mostPopular:true, targetSegment:'subscriber', emotionalHook:'The backbone of jade mastery', scores:{ visual_desirability:8,perceived_value:9,real_margin:6,beginner_friendliness:4,collector_appeal:5,whale_appeal:4,urgency_strength:3,prestige_strength:7,retention_contribution:10,overall_attractiveness:8 } }),
  pack('su-02','Artisan Pass','Monthly crafting pass','subscription_passes','refined','core',300,'⚒️','jade-green',
    [{ name:'Artisan Pass (30 days)',icon:'⚒️',rarity:'refined',qty:1,guaranteed:true },{ name:'Daily Session Token',icon:'🎟️',rarity:'rough',qty:30,guaranteed:true },{ name:'Weekly Tool Kit',icon:'🧰',rarity:'polished',qty:4,guaranteed:true }],
    { priceUsd:4.99, bestValue:true, targetSegment:'crafter', emotionalHook:'Carve every day', scores:{ visual_desirability:6,perceived_value:9,real_margin:5,beginner_friendliness:5,collector_appeal:3,whale_appeal:2,urgency_strength:2,prestige_strength:4,retention_contribution:10,overall_attractiveness:7 } }),
  pack('su-03','Collector Pass','Monthly collector perks','subscription_passes','gilded','mid',400,'🏅','gold',
    [{ name:'Collector Pass (30 days)',icon:'🏅',rarity:'gilded',qty:1,guaranteed:true },{ name:'Weekly Collector Chest',icon:'📦',rarity:'refined',qty:4,guaranteed:true },{ name:'Exclusive Emblem',icon:'🏅',rarity:'gilded',qty:1,guaranteed:true }],
    { priceUsd:7.99, targetSegment:'collector', emotionalHook:'Exclusive collector benefits', scores:{ visual_desirability:7,perceived_value:8,real_margin:6,beginner_friendliness:3,collector_appeal:8,whale_appeal:4,urgency_strength:3,prestige_strength:6,retention_contribution:9,overall_attractiveness:7 } }),
  pack('su-04','Dynasty Membership','Premium annual membership','subscription_passes','imperial','whale',5000,'👑','royal-purple',
    [{ name:'Dynasty Membership (365 days)',icon:'👑',rarity:'imperial',qty:1,guaranteed:true },{ name:'Daily Imperial Drop',icon:'💎',rarity:'refined',qty:365,guaranteed:true },{ name:'Monthly Sovereign Chest',icon:'📦',rarity:'sovereign',qty:12,guaranteed:true },{ name:'Exclusive Dynasty Cosmetics',icon:'✨',rarity:'imperial',qty:1,guaranteed:true }],
    { priceUsd:99.99, featured:true, targetSegment:'whale_subscriber', emotionalHook:'A full year of dynasty privilege', scores:{ visual_desirability:10,perceived_value:10,real_margin:6,beginner_friendliness:1,collector_appeal:9,whale_appeal:9,urgency_strength:4,prestige_strength:10,retention_contribution:10,overall_attractiveness:9 } }),
  pack('su-05','Weekly Vault Stipend','Weekly jade allowance','subscription_passes','polished','entry',80,'📬','jade-green',
    [{ name:'Weekly Stipend (7 days)',icon:'📬',rarity:'polished',qty:1,guaranteed:true },{ name:'Daily Jade Dust',icon:'✨',rarity:'rough',qty:50,guaranteed:true },{ name:'End-of-Week Bonus',icon:'🎁',rarity:'polished',qty:1,guaranteed:true }],
    { priceUsd:1.99, targetSegment:'casual', emotionalHook:'A small weekly ritual', scores:{ visual_desirability:5,perceived_value:7,real_margin:6,beginner_friendliness:7,collector_appeal:2,whale_appeal:1,urgency_strength:3,prestige_strength:2,retention_contribution:8,overall_attractiveness:6 } }),
  pack('su-06','Monthly Jade Reserve Plan','Guaranteed monthly jade','subscription_passes','gilded','mid',600,'🏦','gold-jade',
    [{ name:'Reserve Plan (30 days)',icon:'🏦',rarity:'gilded',qty:1,guaranteed:true },{ name:'Monthly Gilded Jade',icon:'💎',rarity:'gilded',qty:1,guaranteed:true },{ name:'Daily Jade Dust',icon:'✨',rarity:'rough',qty:100,guaranteed:true }],
    { priceUsd:11.99, targetSegment:'investor', emotionalHook:'Guaranteed gilded every month', scores:{ visual_desirability:7,perceived_value:8,real_margin:6,beginner_friendliness:3,collector_appeal:6,whale_appeal:5,urgency_strength:3,prestige_strength:6,retention_contribution:9,overall_attractiveness:7 } }),
  pack('su-07','Trial Pass','3-day trial','subscription_passes','rough','micro',10,'🎟️','jade-green',
    [{ name:'Trial Pass (3 days)',icon:'🎟️',rarity:'rough',qty:1,guaranteed:true },{ name:'Jade Dust',icon:'✨',rarity:'rough',qty:50,guaranteed:true }],
    { purchaseLimit:1, targetSegment:'new_user', emotionalHook:'Try before you commit', scores:{ visual_desirability:4,perceived_value:7,real_margin:4,beginner_friendliness:10,collector_appeal:1,whale_appeal:1,urgency_strength:2,prestige_strength:1,retention_contribution:7,overall_attractiveness:5 } }),
  pack('su-08','Creator Subscription','Monthly creator tools','subscription_passes','sovereign','elite',800,'📐','royal-purple',
    [{ name:'Creator Sub (30 days)',icon:'📐',rarity:'sovereign',qty:1,guaranteed:true },{ name:'Weekly Blueprint Pass',icon:'📐',rarity:'refined',qty:4,guaranteed:true },{ name:'Monthly Reproduction License',icon:'📋',rarity:'gilded',qty:2,guaranteed:true },{ name:'Royalty Boost',icon:'💰',rarity:'refined',qty:1,guaranteed:true }],
    { priceUsd:14.99, targetSegment:'creator', emotionalHook:'Create and earn every month', scores:{ visual_desirability:7,perceived_value:8,real_margin:6,beginner_friendliness:2,collector_appeal:5,whale_appeal:5,urgency_strength:3,prestige_strength:7,retention_contribution:9,overall_attractiveness:7 } }),
  pack('su-09','Jade Dust Drip','Slow daily accumulation','subscription_passes','rough','micro',20,'💧','jade-green',
    [{ name:'Dust Drip (30 days)',icon:'💧',rarity:'rough',qty:1,guaranteed:true },{ name:'Daily Jade Dust',icon:'✨',rarity:'rough',qty:25,guaranteed:true }],
    { priceUsd:0.99, targetSegment:'f2p_convert', emotionalHook:'Less than a dollar, daily jade', scores:{ visual_desirability:3,perceived_value:6,real_margin:7,beginner_friendliness:9,collector_appeal:1,whale_appeal:1,urgency_strength:2,prestige_strength:1,retention_contribution:8,overall_attractiveness:5 } }),
  pack('su-10','Elite Annual Pass','Complete annual access','subscription_passes','imperial','absurd',9000,'🌟','cosmic',
    [{ name:'Elite Annual Pass',icon:'🌟',rarity:'imperial',qty:1,guaranteed:true },{ name:'Dynasty Membership',icon:'👑',rarity:'imperial',qty:1,guaranteed:true },{ name:'Creator Sub',icon:'📐',rarity:'sovereign',qty:1,guaranteed:true },{ name:'Monthly Imperial Chest',icon:'📦',rarity:'imperial',qty:12,guaranteed:true }],
    { priceUsd:179.99, isLimited:true, purchaseLimit:1, targetSegment:'ultra_whale', emotionalHook:'Everything. For a year.', scores:{ visual_desirability:10,perceived_value:10,real_margin:7,beginner_friendliness:1,collector_appeal:9,whale_appeal:10,urgency_strength:5,prestige_strength:10,retention_contribution:10,overall_attractiveness:10 } }),
];

// ── Helper functions for filtering/sorting ──
export function getPacksByCategory(category: JadeStoreCategory): JadePack[] {
  return JADE_STORE_PACKS.filter(p => p.category === category);
}

export function getFeaturedPacks(): JadePack[] {
  return JADE_STORE_PACKS.filter(p => p.featured);
}

export function getBestValuePacks(): JadePack[] {
  return JADE_STORE_PACKS.filter(p => p.bestValue);
}

export function getMostPopularPacks(): JadePack[] {
  return JADE_STORE_PACKS.filter(p => p.mostPopular);
}

export function getLimitedPacks(): JadePack[] {
  return JADE_STORE_PACKS.filter(p => p.isLimited);
}

export function sortByScore(packs: JadePack[], scoreKey: keyof JadePackScores): JadePack[] {
  return [...packs].sort((a, b) => b.scores[scoreKey] - a.scores[scoreKey]);
}
