import type { MediaItem, ConversionJob, OutputAsset, VaultProject } from './types';

export const MOCK_PROJECTS: VaultProject[] = [
  {
    id: 'proj-1',
    name: 'Podcast Season 2',
    description: 'All raw and processed audio for S2',
    color: 'hsl(150 100% 50%)',
    createdAt: '2026-03-20T10:00:00Z',
    updatedAt: '2026-04-05T14:00:00Z',
  },
  {
    id: 'proj-2',
    name: 'Promo Videos',
    description: 'Social clips and trailers',
    color: 'hsl(280 70% 60%)',
    createdAt: '2026-03-28T09:00:00Z',
    updatedAt: '2026-04-04T18:00:00Z',
  },
];

export const MOCK_MEDIA_ITEMS: MediaItem[] = [
  {
    id: 'media-1',
    title: 'Interview Raw Take 3',
    originalFilename: 'interview_take3_final.mp4',
    sourceType: 'uploaded_file',
    importMethod: 'file_upload',
    mimeType: 'video/mp4',
    duration: 1847,
    fileSize: 245_000_000,
    resolution: '1920x1080',
    audioCodec: 'AAC',
    videoCodec: 'H.264',
    status: 'ready',
    tags: ['interview', 'raw', 'season2'],
    notes: 'Best take from March 15 recording session',
    projectId: 'proj-1',
    isFavorite: true,
    createdAt: '2026-03-15T14:30:00Z',
    updatedAt: '2026-03-15T14:30:00Z',
  },
  {
    id: 'media-2',
    title: 'Quick Voice Note',
    originalFilename: 'voice_memo_0402.m4a',
    sourceType: 'recorded_audio',
    importMethod: 'in_app_recording',
    mimeType: 'audio/mp4',
    duration: 45,
    fileSize: 720_000,
    audioCodec: 'AAC',
    status: 'ready',
    tags: ['memo', 'ideas'],
    notes: 'Idea for intro music change',
    isFavorite: false,
    createdAt: '2026-04-02T09:15:00Z',
    updatedAt: '2026-04-02T09:15:00Z',
  },
  {
    id: 'media-3',
    title: 'Product Demo B-Roll',
    originalFilename: 'demo_broll_cam2.mov',
    sourceType: 'camera_roll',
    importMethod: 'photo_library',
    mimeType: 'video/quicktime',
    duration: 312,
    fileSize: 89_000_000,
    resolution: '3840x2160',
    audioCodec: 'PCM',
    videoCodec: 'ProRes',
    status: 'ready',
    tags: ['broll', 'product', 'promo'],
    notes: '',
    projectId: 'proj-2',
    isFavorite: false,
    createdAt: '2026-03-28T16:00:00Z',
    updatedAt: '2026-03-28T16:00:00Z',
  },
  {
    id: 'media-4',
    title: 'Spotify Track Reference',
    originalFilename: '',
    sourceType: 'external_reference_only',
    sourceUrlReference: 'https://open.spotify.com/track/example123',
    importMethod: 'link_paste',
    mimeType: 'text/uri-list',
    fileSize: 0,
    status: 'ready',
    tags: ['reference', 'inspiration'],
    notes: 'Reference track for intro mood',
    isFavorite: false,
    createdAt: '2026-04-01T11:00:00Z',
    updatedAt: '2026-04-01T11:00:00Z',
  },
  {
    id: 'media-5',
    title: 'Background Music Loop',
    originalFilename: 'ambient_loop_v2.wav',
    sourceType: 'uploaded_file',
    importMethod: 'file_upload',
    mimeType: 'audio/wav',
    duration: 180,
    fileSize: 31_000_000,
    audioCodec: 'PCM',
    status: 'ready',
    tags: ['music', 'ambient', 'loop'],
    notes: 'Licensed loop for podcast bed',
    projectId: 'proj-1',
    isFavorite: true,
    createdAt: '2026-03-22T10:00:00Z',
    updatedAt: '2026-03-22T10:00:00Z',
  },
];

export const MOCK_JOBS: ConversionJob[] = [
  {
    id: 'job-1',
    mediaItemId: 'media-1',
    mediaItemTitle: 'Interview Raw Take 3',
    actionType: 'convert_mp3',
    presetKey: 'video_to_mp3',
    outputFormat: 'audio/mpeg',
    targetBitrate: 192,
    normalizationEnabled: false,
    progress: 100,
    status: 'complete',
    createdAt: '2026-03-16T08:00:00Z',
    startedAt: '2026-03-16T08:00:05Z',
    completedAt: '2026-03-16T08:02:30Z',
  },
  {
    id: 'job-2',
    mediaItemId: 'media-3',
    mediaItemTitle: 'Product Demo B-Roll',
    actionType: 'compress_mobile',
    presetKey: 'compress_chat',
    outputFormat: 'video/mp4',
    targetBitrate: 1000,
    normalizationEnabled: false,
    progress: 100,
    status: 'failed',
    errorMessage: 'Codec not supported for this container. Try a different output format.',
    createdAt: '2026-03-29T09:00:00Z',
    startedAt: '2026-03-29T09:00:03Z',
    completedAt: '2026-03-29T09:01:15Z',
  },
  {
    id: 'job-3',
    mediaItemId: 'media-5',
    mediaItemTitle: 'Background Music Loop',
    actionType: 'convert_mp3',
    presetKey: 'video_to_mp3',
    outputFormat: 'audio/mpeg',
    targetBitrate: 320,
    normalizationEnabled: true,
    progress: 62,
    status: 'processing',
    createdAt: '2026-04-06T14:50:00Z',
    startedAt: '2026-04-06T14:50:02Z',
  },
];

export const MOCK_OUTPUTS: OutputAsset[] = [
  {
    id: 'out-1',
    sourceMediaItemId: 'media-1',
    conversionJobId: 'job-1',
    filename: 'interview_take3_final.mp3',
    mimeType: 'audio/mpeg',
    duration: 1847,
    fileSize: 44_400_000,
    storagePath: 'outputs/interview_take3_final.mp3',
    createdAt: '2026-03-16T08:02:30Z',
  },
];
